// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarcodeController from "./barcode_controller"
application.register("barcode", BarcodeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PhotoModalController from "./photo_modal_controller"
application.register("photo-modal", PhotoModalController)

import ScannerLoaderController from "./scanner_loader_controller"
application.register("scanner-loader", ScannerLoaderController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
